apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: sample-app:networking.k8s.io/Ingress:app/sample-app-frontend
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: sample-app-frontend
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.host }}
      http:
        paths:
          - backend:
              service:
                name: sample-app-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: sample-app-backend
                port:
                  number: 5000
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - sample.poetry.com
      secretName: react-tls
